version: '3'
services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: 567234
      MONGO_INITDB_DATABASE: hw06
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongo
volumes:
  mongo-data:
